import sqlite3
con = sqlite3.connect("store.db")
con.execute("DROP TABLE IF EXISTS books;")
con.execute("CREATE TABLE books (id INTEGER, title TEXT NOT NULL, PRIMARY KEY (id));")
con.execute("insert into books (title) values ('Stopařův průvodce po galaxii')")
con.execute("insert into books (title) values ('Den trifidů')")
con.execute("insert into books (title) values ('Mayday')")
con.execute("insert into books (title) values ('Jak věci fungují')")
con.execute("insert into books (title) values ('Kocour Mikeš')")
con.commit()
con.close()
